ZONE_LOOKUP = {
    1: {'Borough': 'EWR', 'Zone': 'Newark Airport', 'service_zone': 'EWR'},
    2: {'Borough': 'Queens', 'Zone': 'Jamaica Bay', 'service_zone': 'Boro Zone'},
    3: {'Borough': 'Bronx',
        'Zone': 'Allerton/Pelham Gardens',
        'service_zone': 'Boro Zone'},
    4: {'Borough': 'Manhattan',
        'Zone': 'Alphabet City',
        'service_zone': 'Yellow Zone'},
    5: {'Borough': 'Staten Island',
        'Zone': 'Arden Heights',
        'service_zone': 'Boro Zone'},
    6: {'Borough': 'Staten Island',
        'Zone': 'Arrochar/Fort Wadsworth',
        'service_zone': 'Boro Zone'},
    7: {'Borough': 'Queens', 'Zone': 'Astoria', 'service_zone': 'Boro Zone'},
    8: {'Borough': 'Queens', 'Zone': 'Astoria Park', 'service_zone': 'Boro Zone'},
    9: {'Borough': 'Queens', 'Zone': 'Auburndale', 'service_zone': 'Boro Zone'},
    10: {'Borough': 'Queens',
         'Zone': 'Baisley Park',
         'service_zone': 'Boro Zone'},
    11: {'Borough': 'Brooklyn',
         'Zone': 'Bath Beach',
         'service_zone': 'Boro Zone'},
    12: {'Borough': 'Manhattan',
         'Zone': 'Battery Park',
         'service_zone': 'Yellow Zone'},
    13: {'Borough': 'Manhattan',
         'Zone': 'Battery Park City',
         'service_zone': 'Yellow Zone'},
    14: {'Borough': 'Brooklyn', 'Zone': 'Bay Ridge', 'service_zone': 'Boro Zone'},
    15: {'Borough': 'Queens',
         'Zone': 'Bay Terrace/Fort Totten',
         'service_zone': 'Boro Zone'},
    16: {'Borough': 'Queens', 'Zone': 'Bayside', 'service_zone': 'Boro Zone'},
    17: {'Borough': 'Brooklyn', 'Zone': 'Bedford', 'service_zone': 'Boro Zone'},
    18: {'Borough': 'Bronx', 'Zone': 'Bedford Park', 'service_zone': 'Boro Zone'},
    19: {'Borough': 'Queens', 'Zone': 'Bellerose', 'service_zone': 'Boro Zone'},
    20: {'Borough': 'Bronx', 'Zone': 'Belmont', 'service_zone': 'Boro Zone'},
    21: {'Borough': 'Brooklyn',
         'Zone': 'Bensonhurst East',
         'service_zone': 'Boro Zone'},
    22: {'Borough': 'Brooklyn',
         'Zone': 'Bensonhurst West',
         'service_zone': 'Boro Zone'},
    23: {'Borough': 'Staten Island',
         'Zone': 'Bloomfield/Emerson Hill',
         'service_zone': 'Boro Zone'},
    24: {'Borough': 'Manhattan',
         'Zone': 'Bloomingdale',
         'service_zone': 'Yellow Zone'},
    25: {'Borough': 'Brooklyn',
         'Zone': 'Boerum Hill',
         'service_zone': 'Boro Zone'},
    26: {'Borough': 'Brooklyn',
         'Zone': 'Borough Park',
         'service_zone': 'Boro Zone'},
    27: {'Borough': 'Queens',
         'Zone': 'Breezy Point/Fort Tilden/Riis Beach',
         'service_zone': 'Boro Zone'},
    28: {'Borough': 'Queens',
         'Zone': 'Briarwood/Jamaica Hills',
         'service_zone': 'Boro Zone'},
    29: {'Borough': 'Brooklyn',
         'Zone': 'Brighton Beach',
         'service_zone': 'Boro Zone'},
    30: {'Borough': 'Queens',
         'Zone': 'Broad Channel',
         'service_zone': 'Boro Zone'},
    31: {'Borough': 'Bronx', 'Zone': 'Bronx Park', 'service_zone': 'Boro Zone'},
    32: {'Borough': 'Bronx', 'Zone': 'Bronxdale', 'service_zone': 'Boro Zone'},
    33: {'Borough': 'Brooklyn',
         'Zone': 'Brooklyn Heights',
         'service_zone': 'Boro Zone'},
    34: {'Borough': 'Brooklyn',
         'Zone': 'Brooklyn Navy Yard',
         'service_zone': 'Boro Zone'},
    35: {'Borough': 'Brooklyn',
         'Zone': 'Brownsville',
         'service_zone': 'Boro Zone'},
    36: {'Borough': 'Brooklyn',
         'Zone': 'Bushwick North',
         'service_zone': 'Boro Zone'},
    37: {'Borough': 'Brooklyn',
         'Zone': 'Bushwick South',
         'service_zone': 'Boro Zone'},
    38: {'Borough': 'Queens',
         'Zone': 'Cambria Heights',
         'service_zone': 'Boro Zone'},
    39: {'Borough': 'Brooklyn', 'Zone': 'Canarsie', 'service_zone': 'Boro Zone'},
    40: {'Borough': 'Brooklyn',
         'Zone': 'Carroll Gardens',
         'service_zone': 'Boro Zone'},
    41: {'Borough': 'Manhattan',
         'Zone': 'Central Harlem',
         'service_zone': 'Boro Zone'},
    42: {'Borough': 'Manhattan',
         'Zone': 'Central Harlem North',
         'service_zone': 'Boro Zone'},
    43: {'Borough': 'Manhattan',
         'Zone': 'Central Park',
         'service_zone': 'Yellow Zone'},
    44: {'Borough': 'Staten Island',
         'Zone': 'Charleston/Tottenville',
         'service_zone': 'Boro Zone'},
    45: {'Borough': 'Manhattan',
         'Zone': 'Chinatown',
         'service_zone': 'Yellow Zone'},
    46: {'Borough': 'Bronx', 'Zone': 'City Island', 'service_zone': 'Boro Zone'},
    47: {'Borough': 'Bronx',
         'Zone': 'Claremont/Bathgate',
         'service_zone': 'Boro Zone'},
    48: {'Borough': 'Manhattan',
         'Zone': 'Clinton East',
         'service_zone': 'Yellow Zone'},
    49: {'Borough': 'Brooklyn',
         'Zone': 'Clinton Hill',
         'service_zone': 'Boro Zone'},
    50: {'Borough': 'Manhattan',
         'Zone': 'Clinton West',
         'service_zone': 'Yellow Zone'},
    51: {'Borough': 'Bronx', 'Zone': 'Co-Op City', 'service_zone': 'Boro Zone'},
    52: {'Borough': 'Brooklyn',
         'Zone': 'Cobble Hill',
         'service_zone': 'Boro Zone'},
    53: {'Borough': 'Queens',
         'Zone': 'College Point',
         'service_zone': 'Boro Zone'},
    54: {'Borough': 'Brooklyn',
         'Zone': 'Columbia Street',
         'service_zone': 'Boro Zone'},
    55: {'Borough': 'Brooklyn',
         'Zone': 'Coney Island',
         'service_zone': 'Boro Zone'},
    56: {'Borough': 'Queens', 'Zone': 'Corona', 'service_zone': 'Boro Zone'},
    57: {'Borough': 'Queens', 'Zone': 'Corona', 'service_zone': 'Boro Zone'},
    58: {'Borough': 'Bronx', 'Zone': 'Country Club', 'service_zone': 'Boro Zone'},
    59: {'Borough': 'Bronx', 'Zone': 'Crotona Park', 'service_zone': 'Boro Zone'},
    60: {'Borough': 'Bronx',
         'Zone': 'Crotona Park East',
         'service_zone': 'Boro Zone'},
    61: {'Borough': 'Brooklyn',
         'Zone': 'Crown Heights North',
         'service_zone': 'Boro Zone'},
    62: {'Borough': 'Brooklyn',
         'Zone': 'Crown Heights South',
         'service_zone': 'Boro Zone'},
    63: {'Borough': 'Brooklyn',
         'Zone': 'Cypress Hills',
         'service_zone': 'Boro Zone'},
    64: {'Borough': 'Queens', 'Zone': 'Douglaston', 'service_zone': 'Boro Zone'},
    65: {'Borough': 'Brooklyn',
         'Zone': 'Downtown Brooklyn/MetroTech',
         'service_zone': 'Boro Zone'},
    66: {'Borough': 'Brooklyn',
         'Zone': 'DUMBO/Vinegar Hill',
         'service_zone': 'Boro Zone'},
    67: {'Borough': 'Brooklyn',
         'Zone': 'Dyker Heights',
         'service_zone': 'Boro Zone'},
    68: {'Borough': 'Manhattan',
         'Zone': 'East Chelsea',
         'service_zone': 'Yellow Zone'},
    69: {'Borough': 'Bronx',
         'Zone': 'East Concourse/Concourse Village',
         'service_zone': 'Boro Zone'},
    70: {'Borough': 'Queens',
         'Zone': 'East Elmhurst',
         'service_zone': 'Boro Zone'},
    71: {'Borough': 'Brooklyn',
         'Zone': 'East Flatbush/Farragut',
         'service_zone': 'Boro Zone'},
    72: {'Borough': 'Brooklyn',
         'Zone': 'East Flatbush/Remsen Village',
         'service_zone': 'Boro Zone'},
    73: {'Borough': 'Queens',
         'Zone': 'East Flushing',
         'service_zone': 'Boro Zone'},
    74: {'Borough': 'Manhattan',
         'Zone': 'East Harlem North',
         'service_zone': 'Boro Zone'},
    75: {'Borough': 'Manhattan',
         'Zone': 'East Harlem South',
         'service_zone': 'Boro Zone'},
    76: {'Borough': 'Brooklyn',
         'Zone': 'East New York',
         'service_zone': 'Boro Zone'},
    77: {'Borough': 'Brooklyn',
         'Zone': 'East New York/Pennsylvania Avenue',
         'service_zone': 'Boro Zone'},
    78: {'Borough': 'Bronx', 'Zone': 'East Tremont', 'service_zone': 'Boro Zone'},
    79: {'Borough': 'Manhattan',
         'Zone': 'East Village',
         'service_zone': 'Yellow Zone'},
    80: {'Borough': 'Brooklyn',
         'Zone': 'East Williamsburg',
         'service_zone': 'Boro Zone'},
    81: {'Borough': 'Bronx', 'Zone': 'Eastchester', 'service_zone': 'Boro Zone'},
    82: {'Borough': 'Queens', 'Zone': 'Elmhurst', 'service_zone': 'Boro Zone'},
    83: {'Borough': 'Queens',
         'Zone': 'Elmhurst/Maspeth',
         'service_zone': 'Boro Zone'},
    84: {'Borough': 'Staten Island',
         'Zone': "Eltingville/Annadale/Prince's Bay",
         'service_zone': 'Boro Zone'},
    85: {'Borough': 'Brooklyn', 'Zone': 'Erasmus', 'service_zone': 'Boro Zone'},
    86: {'Borough': 'Queens',
         'Zone': 'Far Rockaway',
         'service_zone': 'Boro Zone'},
    87: {'Borough': 'Manhattan',
         'Zone': 'Financial District North',
         'service_zone': 'Yellow Zone'},
    88: {'Borough': 'Manhattan',
         'Zone': 'Financial District South',
         'service_zone': 'Yellow Zone'},
    89: {'Borough': 'Brooklyn',
         'Zone': 'Flatbush/Ditmas Park',
         'service_zone': 'Boro Zone'},
    90: {'Borough': 'Manhattan',
         'Zone': 'Flatiron',
         'service_zone': 'Yellow Zone'},
    91: {'Borough': 'Brooklyn', 'Zone': 'Flatlands', 'service_zone': 'Boro Zone'},
    92: {'Borough': 'Queens', 'Zone': 'Flushing', 'service_zone': 'Boro Zone'},
    93: {'Borough': 'Queens',
         'Zone': 'Flushing Meadows-Corona Park',
         'service_zone': 'Boro Zone'},
    94: {'Borough': 'Bronx',
         'Zone': 'Fordham South',
         'service_zone': 'Boro Zone'},
    95: {'Borough': 'Queens',
         'Zone': 'Forest Hills',
         'service_zone': 'Boro Zone'},
    96: {'Borough': 'Queens',
         'Zone': 'Forest Park/Highland Park',
         'service_zone': 'Boro Zone'},
    97: {'Borough': 'Brooklyn',
         'Zone': 'Fort Greene',
         'service_zone': 'Boro Zone'},
    98: {'Borough': 'Queens',
         'Zone': 'Fresh Meadows',
         'service_zone': 'Boro Zone'},
    99: {'Borough': 'Staten Island',
         'Zone': 'Freshkills Park',
         'service_zone': 'Boro Zone'},
    100: {'Borough': 'Manhattan',
          'Zone': 'Garment District',
          'service_zone': 'Yellow Zone'},
    101: {'Borough': 'Queens', 'Zone': 'Glen Oaks', 'service_zone': 'Boro Zone'},
    102: {'Borough': 'Queens', 'Zone': 'Glendale', 'service_zone': 'Boro Zone'},
    103: {'Borough': 'Manhattan',
          'Zone': "Governor's Island/Ellis Island/Liberty Island",
          'service_zone': 'Yellow Zone'},
    104: {'Borough': 'Manhattan',
          'Zone': "Governor's Island/Ellis Island/Liberty Island",
          'service_zone': 'Yellow Zone'},
    105: {'Borough': 'Manhattan',
          'Zone': "Governor's Island/Ellis Island/Liberty Island",
          'service_zone': 'Yellow Zone'},
    106: {'Borough': 'Brooklyn', 'Zone': 'Gowanus', 'service_zone': 'Boro Zone'},
    107: {'Borough': 'Manhattan',
          'Zone': 'Gramercy',
          'service_zone': 'Yellow Zone'},
    108: {'Borough': 'Brooklyn',
          'Zone': 'Gravesend',
          'service_zone': 'Boro Zone'},
    109: {'Borough': 'Staten Island',
          'Zone': 'Great Kills',
          'service_zone': 'Boro Zone'},
    110: {'Borough': 'Staten Island',
          'Zone': 'Great Kills Park',
          'service_zone': 'Boro Zone'},
    111: {'Borough': 'Brooklyn',
          'Zone': 'Green-Wood Cemetery',
          'service_zone': 'Boro Zone'},
    112: {'Borough': 'Brooklyn',
          'Zone': 'Greenpoint',
          'service_zone': 'Boro Zone'},
    113: {'Borough': 'Manhattan',
          'Zone': 'Greenwich Village North',
          'service_zone': 'Yellow Zone'},
    114: {'Borough': 'Manhattan',
          'Zone': 'Greenwich Village South',
          'service_zone': 'Yellow Zone'},
    115: {'Borough': 'Staten Island',
          'Zone': 'Grymes Hill/Clifton',
          'service_zone': 'Boro Zone'},
    116: {'Borough': 'Manhattan',
          'Zone': 'Hamilton Heights',
          'service_zone': 'Boro Zone'},
    117: {'Borough': 'Queens',
          'Zone': 'Hammels/Arverne',
          'service_zone': 'Boro Zone'},
    118: {'Borough': 'Staten Island',
          'Zone': 'Heartland Village/Todt Hill',
          'service_zone': 'Boro Zone'},
    119: {'Borough': 'Bronx', 'Zone': 'Highbridge', 'service_zone': 'Boro Zone'},
    120: {'Borough': 'Manhattan',
          'Zone': 'Highbridge Park',
          'service_zone': 'Boro Zone'},
    121: {'Borough': 'Queens',
          'Zone': 'Hillcrest/Pomonok',
          'service_zone': 'Boro Zone'},
    122: {'Borough': 'Queens', 'Zone': 'Hollis', 'service_zone': 'Boro Zone'},
    123: {'Borough': 'Brooklyn',
          'Zone': 'Homecrest',
          'service_zone': 'Boro Zone'},
    124: {'Borough': 'Queens',
          'Zone': 'Howard Beach',
          'service_zone': 'Boro Zone'},
    125: {'Borough': 'Manhattan',
          'Zone': 'Hudson Sq',
          'service_zone': 'Yellow Zone'},
    126: {'Borough': 'Bronx', 'Zone': 'Hunts Point', 'service_zone': 'Boro Zone'},
    127: {'Borough': 'Manhattan', 'Zone': 'Inwood', 'service_zone': 'Boro Zone'},
    128: {'Borough': 'Manhattan',
          'Zone': 'Inwood Hill Park',
          'service_zone': 'Boro Zone'},
    129: {'Borough': 'Queens',
          'Zone': 'Jackson Heights',
          'service_zone': 'Boro Zone'},
    130: {'Borough': 'Queens', 'Zone': 'Jamaica', 'service_zone': 'Boro Zone'},
    131: {'Borough': 'Queens',
          'Zone': 'Jamaica Estates',
          'service_zone': 'Boro Zone'},
    132: {'Borough': 'Queens', 'Zone': 'JFK Airport', 'service_zone': 'Airports'},
    133: {'Borough': 'Brooklyn',
          'Zone': 'Kensington',
          'service_zone': 'Boro Zone'},
    134: {'Borough': 'Queens',
          'Zone': 'Kew Gardens',
          'service_zone': 'Boro Zone'},
    135: {'Borough': 'Queens',
          'Zone': 'Kew Gardens Hills',
          'service_zone': 'Boro Zone'},
    136: {'Borough': 'Bronx',
          'Zone': 'Kingsbridge Heights',
          'service_zone': 'Boro Zone'},
    137: {'Borough': 'Manhattan',
          'Zone': 'Kips Bay',
          'service_zone': 'Yellow Zone'},
    138: {'Borough': 'Queens',
          'Zone': 'LaGuardia Airport',
          'service_zone': 'Airports'},
    139: {'Borough': 'Queens', 'Zone': 'Laurelton', 'service_zone': 'Boro Zone'},
    140: {'Borough': 'Manhattan',
          'Zone': 'Lenox Hill East',
          'service_zone': 'Yellow Zone'},
    141: {'Borough': 'Manhattan',
          'Zone': 'Lenox Hill West',
          'service_zone': 'Yellow Zone'},
    142: {'Borough': 'Manhattan',
          'Zone': 'Lincoln Square East',
          'service_zone': 'Yellow Zone'},
    143: {'Borough': 'Manhattan',
          'Zone': 'Lincoln Square West',
          'service_zone': 'Yellow Zone'},
    144: {'Borough': 'Manhattan',
          'Zone': 'Little Italy/NoLiTa',
          'service_zone': 'Yellow Zone'},
    145: {'Borough': 'Queens',
          'Zone': 'Long Island City/Hunters Point',
          'service_zone': 'Boro Zone'},
    146: {'Borough': 'Queens',
          'Zone': 'Long Island City/Queens Plaza',
          'service_zone': 'Boro Zone'},
    147: {'Borough': 'Bronx', 'Zone': 'Longwood', 'service_zone': 'Boro Zone'},
    148: {'Borough': 'Manhattan',
          'Zone': 'Lower East Side',
          'service_zone': 'Yellow Zone'},
    149: {'Borough': 'Brooklyn', 'Zone': 'Madison', 'service_zone': 'Boro Zone'},
    150: {'Borough': 'Brooklyn',
          'Zone': 'Manhattan Beach',
          'service_zone': 'Boro Zone'},
    151: {'Borough': 'Manhattan',
          'Zone': 'Manhattan Valley',
          'service_zone': 'Yellow Zone'},
    152: {'Borough': 'Manhattan',
          'Zone': 'Manhattanville',
          'service_zone': 'Boro Zone'},
    153: {'Borough': 'Manhattan',
          'Zone': 'Marble Hill',
          'service_zone': 'Boro Zone'},
    154: {'Borough': 'Brooklyn',
          'Zone': 'Marine Park/Floyd Bennett Field',
          'service_zone': 'Boro Zone'},
    155: {'Borough': 'Brooklyn',
          'Zone': 'Marine Park/Mill Basin',
          'service_zone': 'Boro Zone'},
    156: {'Borough': 'Staten Island',
          'Zone': 'Mariners Harbor',
          'service_zone': 'Boro Zone'},
    157: {'Borough': 'Queens', 'Zone': 'Maspeth', 'service_zone': 'Boro Zone'},
    158: {'Borough': 'Manhattan',
          'Zone': 'Meatpacking/West Village West',
          'service_zone': 'Yellow Zone'},
    159: {'Borough': 'Bronx',
          'Zone': 'Melrose South',
          'service_zone': 'Boro Zone'},
    160: {'Borough': 'Queens',
          'Zone': 'Middle Village',
          'service_zone': 'Boro Zone'},
    161: {'Borough': 'Manhattan',
          'Zone': 'Midtown Center',
          'service_zone': 'Yellow Zone'},
    162: {'Borough': 'Manhattan',
          'Zone': 'Midtown East',
          'service_zone': 'Yellow Zone'},
    163: {'Borough': 'Manhattan',
          'Zone': 'Midtown North',
          'service_zone': 'Yellow Zone'},
    164: {'Borough': 'Manhattan',
          'Zone': 'Midtown South',
          'service_zone': 'Yellow Zone'},
    165: {'Borough': 'Brooklyn', 'Zone': 'Midwood', 'service_zone': 'Boro Zone'},
    166: {'Borough': 'Manhattan',
          'Zone': 'Morningside Heights',
          'service_zone': 'Boro Zone'},
    167: {'Borough': 'Bronx',
          'Zone': 'Morrisania/Melrose',
          'service_zone': 'Boro Zone'},
    168: {'Borough': 'Bronx',
          'Zone': 'Mott Haven/Port Morris',
          'service_zone': 'Boro Zone'},
    169: {'Borough': 'Bronx', 'Zone': 'Mount Hope', 'service_zone': 'Boro Zone'},
    170: {'Borough': 'Manhattan',
          'Zone': 'Murray Hill',
          'service_zone': 'Yellow Zone'},
    171: {'Borough': 'Queens',
          'Zone': 'Murray Hill-Queens',
          'service_zone': 'Boro Zone'},
    172: {'Borough': 'Staten Island',
          'Zone': 'New Dorp/Midland Beach',
          'service_zone': 'Boro Zone'},
    173: {'Borough': 'Queens',
          'Zone': 'North Corona',
          'service_zone': 'Boro Zone'},
    174: {'Borough': 'Bronx', 'Zone': 'Norwood', 'service_zone': 'Boro Zone'},
    175: {'Borough': 'Queens',
          'Zone': 'Oakland Gardens',
          'service_zone': 'Boro Zone'},
    176: {'Borough': 'Staten Island',
          'Zone': 'Oakwood',
          'service_zone': 'Boro Zone'},
    177: {'Borough': 'Brooklyn',
          'Zone': 'Ocean Hill',
          'service_zone': 'Boro Zone'},
    178: {'Borough': 'Brooklyn',
          'Zone': 'Ocean Parkway South',
          'service_zone': 'Boro Zone'},
    179: {'Borough': 'Queens',
          'Zone': 'Old Astoria',
          'service_zone': 'Boro Zone'},
    180: {'Borough': 'Queens', 'Zone': 'Ozone Park', 'service_zone': 'Boro Zone'},
    181: {'Borough': 'Brooklyn',
          'Zone': 'Park Slope',
          'service_zone': 'Boro Zone'},
    182: {'Borough': 'Bronx', 'Zone': 'Parkchester', 'service_zone': 'Boro Zone'},
    183: {'Borough': 'Bronx', 'Zone': 'Pelham Bay', 'service_zone': 'Boro Zone'},
    184: {'Borough': 'Bronx',
          'Zone': 'Pelham Bay Park',
          'service_zone': 'Boro Zone'},
    185: {'Borough': 'Bronx',
          'Zone': 'Pelham Parkway',
          'service_zone': 'Boro Zone'},
    186: {'Borough': 'Manhattan',
          'Zone': 'Penn Station/Madison Sq West',
          'service_zone': 'Yellow Zone'},
    187: {'Borough': 'Staten Island',
          'Zone': 'Port Richmond',
          'service_zone': 'Boro Zone'},
    188: {'Borough': 'Brooklyn',
          'Zone': 'Prospect-Lefferts Gardens',
          'service_zone': 'Boro Zone'},
    189: {'Borough': 'Brooklyn',
          'Zone': 'Prospect Heights',
          'service_zone': 'Boro Zone'},
    190: {'Borough': 'Brooklyn',
          'Zone': 'Prospect Park',
          'service_zone': 'Boro Zone'},
    191: {'Borough': 'Queens',
          'Zone': 'Queens Village',
          'service_zone': 'Boro Zone'},
    192: {'Borough': 'Queens',
          'Zone': 'Queensboro Hill',
          'service_zone': 'Boro Zone'},
    193: {'Borough': 'Queens',
          'Zone': 'Queensbridge/Ravenswood',
          'service_zone': 'Boro Zone'},
    194: {'Borough': 'Manhattan',
          'Zone': 'Randalls Island',
          'service_zone': 'Yellow Zone'},
    195: {'Borough': 'Brooklyn', 'Zone': 'Red Hook', 'service_zone': 'Boro Zone'},
    196: {'Borough': 'Queens', 'Zone': 'Rego Park', 'service_zone': 'Boro Zone'},
    197: {'Borough': 'Queens',
          'Zone': 'Richmond Hill',
          'service_zone': 'Boro Zone'},
    198: {'Borough': 'Queens', 'Zone': 'Ridgewood', 'service_zone': 'Boro Zone'},
    199: {'Borough': 'Bronx',
          'Zone': 'Rikers Island',
          'service_zone': 'Boro Zone'},
    200: {'Borough': 'Bronx',
          'Zone': 'Riverdale/North Riverdale/Fieldston',
          'service_zone': 'Boro Zone'},
    201: {'Borough': 'Queens',
          'Zone': 'Rockaway Park',
          'service_zone': 'Boro Zone'},
    202: {'Borough': 'Manhattan',
          'Zone': 'Roosevelt Island',
          'service_zone': 'Boro Zone'},
    203: {'Borough': 'Queens', 'Zone': 'Rosedale', 'service_zone': 'Boro Zone'},
    204: {'Borough': 'Staten Island',
          'Zone': 'Rossville/Woodrow',
          'service_zone': 'Boro Zone'},
    205: {'Borough': 'Queens',
          'Zone': 'Saint Albans',
          'service_zone': 'Boro Zone'},
    206: {'Borough': 'Staten Island',
          'Zone': 'Saint George/New Brighton',
          'service_zone': 'Boro Zone'},
    207: {'Borough': 'Queens',
          'Zone': 'Saint Michaels Cemetery/Woodside',
          'service_zone': 'Boro Zone'},
    208: {'Borough': 'Bronx',
          'Zone': 'Schuylerville/Edgewater Park',
          'service_zone': 'Boro Zone'},
    209: {'Borough': 'Manhattan',
          'Zone': 'Seaport',
          'service_zone': 'Yellow Zone'},
    210: {'Borough': 'Brooklyn',
          'Zone': 'Sheepshead Bay',
          'service_zone': 'Boro Zone'},
    211: {'Borough': 'Manhattan', 'Zone': 'SoHo', 'service_zone': 'Yellow Zone'},
    212: {'Borough': 'Bronx',
          'Zone': 'Soundview/Bruckner',
          'service_zone': 'Boro Zone'},
    213: {'Borough': 'Bronx',
          'Zone': 'Soundview/Castle Hill',
          'service_zone': 'Boro Zone'},
    214: {'Borough': 'Staten Island',
          'Zone': 'South Beach/Dongan Hills',
          'service_zone': 'Boro Zone'},
    215: {'Borough': 'Queens',
          'Zone': 'South Jamaica',
          'service_zone': 'Boro Zone'},
    216: {'Borough': 'Queens',
          'Zone': 'South Ozone Park',
          'service_zone': 'Boro Zone'},
    217: {'Borough': 'Brooklyn',
          'Zone': 'South Williamsburg',
          'service_zone': 'Boro Zone'},
    218: {'Borough': 'Queens',
          'Zone': 'Springfield Gardens North',
          'service_zone': 'Boro Zone'},
    219: {'Borough': 'Queens',
          'Zone': 'Springfield Gardens South',
          'service_zone': 'Boro Zone'},
    220: {'Borough': 'Bronx',
          'Zone': 'Spuyten Duyvil/Kingsbridge',
          'service_zone': 'Boro Zone'},
    221: {'Borough': 'Staten Island',
          'Zone': 'Stapleton',
          'service_zone': 'Boro Zone'},
    222: {'Borough': 'Brooklyn',
          'Zone': 'Starrett City',
          'service_zone': 'Boro Zone'},
    223: {'Borough': 'Queens', 'Zone': 'Steinway', 'service_zone': 'Boro Zone'},
    224: {'Borough': 'Manhattan',
          'Zone': 'Stuy Town/Peter Cooper Village',
          'service_zone': 'Yellow Zone'},
    225: {'Borough': 'Brooklyn',
          'Zone': 'Stuyvesant Heights',
          'service_zone': 'Boro Zone'},
    226: {'Borough': 'Queens', 'Zone': 'Sunnyside', 'service_zone': 'Boro Zone'},
    227: {'Borough': 'Brooklyn',
          'Zone': 'Sunset Park East',
          'service_zone': 'Boro Zone'},
    228: {'Borough': 'Brooklyn',
          'Zone': 'Sunset Park West',
          'service_zone': 'Boro Zone'},
    229: {'Borough': 'Manhattan',
          'Zone': 'Sutton Place/Turtle Bay North',
          'service_zone': 'Yellow Zone'},
    230: {'Borough': 'Manhattan',
          'Zone': 'Times Sq/Theatre District',
          'service_zone': 'Yellow Zone'},
    231: {'Borough': 'Manhattan',
          'Zone': 'TriBeCa/Civic Center',
          'service_zone': 'Yellow Zone'},
    232: {'Borough': 'Manhattan',
          'Zone': 'Two Bridges/Seward Park',
          'service_zone': 'Yellow Zone'},
    233: {'Borough': 'Manhattan',
          'Zone': 'UN/Turtle Bay South',
          'service_zone': 'Yellow Zone'},
    234: {'Borough': 'Manhattan',
          'Zone': 'Union Sq',
          'service_zone': 'Yellow Zone'},
    235: {'Borough': 'Bronx',
          'Zone': 'University Heights/Morris Heights',
          'service_zone': 'Boro Zone'},
    236: {'Borough': 'Manhattan',
          'Zone': 'Upper East Side North',
          'service_zone': 'Yellow Zone'},
    237: {'Borough': 'Manhattan',
          'Zone': 'Upper East Side South',
          'service_zone': 'Yellow Zone'},
    238: {'Borough': 'Manhattan',
          'Zone': 'Upper West Side North',
          'service_zone': 'Yellow Zone'},
    239: {'Borough': 'Manhattan',
          'Zone': 'Upper West Side South',
          'service_zone': 'Yellow Zone'},
    240: {'Borough': 'Bronx',
          'Zone': 'Van Cortlandt Park',
          'service_zone': 'Boro Zone'},
    241: {'Borough': 'Bronx',
          'Zone': 'Van Cortlandt Village',
          'service_zone': 'Boro Zone'},
    242: {'Borough': 'Bronx',
          'Zone': 'Van Nest/Morris Park',
          'service_zone': 'Boro Zone'},
    243: {'Borough': 'Manhattan',
          'Zone': 'Washington Heights North',
          'service_zone': 'Boro Zone'},
    244: {'Borough': 'Manhattan',
          'Zone': 'Washington Heights South',
          'service_zone': 'Boro Zone'},
    245: {'Borough': 'Staten Island',
          'Zone': 'West Brighton',
          'service_zone': 'Boro Zone'},
    246: {'Borough': 'Manhattan',
          'Zone': 'West Chelsea/Hudson Yards',
          'service_zone': 'Yellow Zone'},
    247: {'Borough': 'Bronx',
          'Zone': 'West Concourse',
          'service_zone': 'Boro Zone'},
    248: {'Borough': 'Bronx',
          'Zone': 'West Farms/Bronx River',
          'service_zone': 'Boro Zone'},
    249: {'Borough': 'Manhattan',
          'Zone': 'West Village',
          'service_zone': 'Yellow Zone'},
    250: {'Borough': 'Bronx',
          'Zone': 'Westchester Village/Unionport',
          'service_zone': 'Boro Zone'},
    251: {'Borough': 'Staten Island',
          'Zone': 'Westerleigh',
          'service_zone': 'Boro Zone'},
    252: {'Borough': 'Queens', 'Zone': 'Whitestone', 'service_zone': 'Boro Zone'},
    253: {'Borough': 'Queens',
          'Zone': 'Willets Point',
          'service_zone': 'Boro Zone'},
    254: {'Borough': 'Bronx',
          'Zone': 'Williamsbridge/Olinville',
          'service_zone': 'Boro Zone'},
    255: {'Borough': 'Brooklyn',
          'Zone': 'Williamsburg (North Side)',
          'service_zone': 'Boro Zone'},
    256: {'Borough': 'Brooklyn',
          'Zone': 'Williamsburg (South Side)',
          'service_zone': 'Boro Zone'},
    257: {'Borough': 'Brooklyn',
          'Zone': 'Windsor Terrace',
          'service_zone': 'Boro Zone'},
    258: {'Borough': 'Queens', 'Zone': 'Woodhaven', 'service_zone': 'Boro Zone'},
    259: {'Borough': 'Bronx',
          'Zone': 'Woodlawn/Wakefield',
          'service_zone': 'Boro Zone'},
    260: {'Borough': 'Queens', 'Zone': 'Woodside', 'service_zone': 'Boro Zone'},
    261: {'Borough': 'Manhattan',
          'Zone': 'World Trade Center',
          'service_zone': 'Yellow Zone'},
    262: {'Borough': 'Manhattan',
          'Zone': 'Yorkville East',
          'service_zone': 'Yellow Zone'},
    263: {'Borough': 'Manhattan',
          'Zone': 'Yorkville West',
          'service_zone': 'Yellow Zone'},
    264: {'Borough': 'Unknown', 'Zone': 'NV', 'service_zone': None},
    265: {'Borough': 'Unknown', 'Zone': None, 'service_zone': None}
}
