"""initial version

Revision ID: 25012ced96b3
Revises: 
Create Date: 2022-08-28 01:02:40.579931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import app

revision = '25012ced96b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weatherdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('resolved_address', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('precip', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weatherdata_id'), 'weatherdata', ['id'], unique=False)
    op.create_index(op.f('ix_weatherdata_location'), 'weatherdata', ['location'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weatherdata_location'), table_name='weatherdata')
    op.drop_index(op.f('ix_weatherdata_id'), table_name='weatherdata')
    op.drop_table('weatherdata')
    # ### end Alembic commands ###
