"""location not unique

Revision ID: d82d01d09e2a
Revises: 25012ced96b3
Create Date: 2022-08-28 23:23:53.576693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82d01d09e2a'
down_revision = '25012ced96b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weatherdata_location', table_name='weatherdata')
    op.create_index(op.f('ix_weatherdata_location'), 'weatherdata', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weatherdata_location'), table_name='weatherdata')
    op.create_index('ix_weatherdata_location', 'weatherdata', ['location'], unique=False)
    # ### end Alembic commands ###
