"""first commit

Revision ID: 54ff1de11551
Revises: 
Create Date: 2022-08-26 21:37:01.868651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ff1de11551'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('borough', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('tpep_pickup_datetime', sa.DateTime(), nullable=True),
    sa.Column('tpep_dropoff_datetime', sa.DateTime(), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('trip_distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pickup_location_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=False),
    sa.Column('rate_code_id', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.Integer(), nullable=True),
    sa.Column('fare_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mta_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tip_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tolls_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('improvement_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('congestion_surcharge', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('airport_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_id'), 'receipt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_id'), table_name='receipt')
    op.drop_table('receipt')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
